"""empty message

Revision ID: 5fe8508c3e63
Revises: dd66578efb26
Create Date: 2021-01-20 05:05:35.918040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe8508c3e63'
down_revision = 'dd66578efb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hand', sa.Column('dealt', sa.String(length=15), nullable=True))
    op.create_index(op.f('ix_hand_dealt'), 'hand', ['dealt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hand_dealt'), table_name='hand')
    op.drop_column('hand', 'dealt')
    # ### end Alembic commands ###
