"""Added fields to user model.

Revision ID: 7e66df474655
Revises: fc83dad1ce55
Create Date: 2020-05-03 22:51:42.595572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e66df474655'
down_revision = 'fc83dad1ce55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('balance', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('joined', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('losses', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('status', sa.String(length=16), nullable=True))
    op.add_column('user', sa.Column('wins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'wins')
    op.drop_column('user', 'status')
    op.drop_column('user', 'points')
    op.drop_column('user', 'losses')
    op.drop_column('user', 'joined')
    op.drop_column('user', 'balance')
    # ### end Alembic commands ###
