"""Hand table

Revision ID: 847f8a0e60fb
Revises: 7e66df474655
Create Date: 2020-05-16 23:50:55.877278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847f8a0e60fb'
down_revision = '7e66df474655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hand', sa.String(length=15), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hand_hand'), 'hand', ['hand'], unique=False)
    op.create_index(op.f('ix_hand_timestamp'), 'hand', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hand_timestamp'), table_name='hand')
    op.drop_index(op.f('ix_hand_hand'), table_name='hand')
    op.drop_table('hand')
    # ### end Alembic commands ###
