"""Add bet tally to User

Revision ID: dd66578efb26
Revises: 847f8a0e60fb
Create Date: 2020-05-17 08:37:06.638588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd66578efb26'
down_revision = '847f8a0e60fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bet', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bet')
    # ### end Alembic commands ###
